#!/usr/bin/env python3
"""
Unified Credential Setup for TidyLLM
====================================

CONSOLIDATES ALL SCATTERED CREDENTIAL SETUP PATTERNS
====================================================

Replaces and consolidates:
- scripts/setup_aws_credentials.py
- scripts/set_aws_credentials.py
- scripts/verify_aws_credentials.py
- tidyllm/admin/set_aws_credentials.py
- tidyllm/demo-standalone/credential_manager.py

Uses official UnifiedSessionManager for all credential validation.
Creates unified environment setup that works across the entire TidyLLM ecosystem.
"""

import os
import sys
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional
import tempfile

# Add project root for UnifiedSessionManager import
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# Import official UnifiedSessionManager
try:
    from scripts.start_unified_sessions import UnifiedSessionManager
    UNIFIED_SESSION_AVAILABLE = True
except ImportError:
    UNIFIED_SESSION_AVAILABLE = False

class UnifiedCredentialSetup:
    """
    Unified credential setup using UnifiedSessionManager architecture
    
    No longer creates scattered credential management patterns.
    All validation goes through official UnifiedSessionManager.
    """
    
    def __init__(self):
        """Initialize with UnifiedSessionManager"""
        self.credentials = {
            # Credentials loaded by centralized system,
            # Credentials loaded by centralized system,
            # Credentials loaded by centralized system,
            'POSTGRES_HOST': 'localhost',
            'POSTGRES_PORT': '5432',
            'POSTGRES_DB': 'mlflow',
            'POSTGRES_USER': 'mlflowuser',
            'POSTGRES_PASSWORD': 'mlflowpass',
            'MLFLOW_TRACKING_URI': 'postgresql://mlflowuser:mlflowpass@localhost:5432/mlflowdb'
        }
        
        # Only validate with UnifiedSessionManager if available
        if UNIFIED_SESSION_AVAILABLE:
            self.session_mgr = UnifiedSessionManager()
        else:
            self.session_mgr = None
            print("⚠️ UnifiedSessionManager not available - setup will proceed without validation")
    
    def set_environment_variables(self, persist: bool = False) -> bool:
        """Set environment variables for current session and optionally persist"""
        
        print("🔧 Setting TidyLLM environment variables...")
        
        # Set variables in current process
        for key, value in self.credentials.items():
            os.environ[key] = value
            print(f"✅ {key}={'*' * 8}...")  # Mask sensitive values
        
        if persist:
            self._create_persistent_setup()
        
        print("✅ Environment variables configured")
        return True
    
    def _create_persistent_setup(self):
        """Create persistent setup scripts for different platforms"""
        
        # Windows batch file
        windows_script = project_root / "tidyllm" / "admin" / "set_aws_env.bat"
        windows_script.parent.mkdir(exist_ok=True)
        
        with open(windows_script, 'w') as f:
            f.write("@echo off\n")
            f.write("REM TidyLLM Unified Environment Setup (Windows)\n")
            f.write("REM Generated by unified_credential_setup.py\n\n")
            
            for key, value in self.credentials.items():
                f.write(f'set {key}={value}\n')
            
            f.write('\necho ✅ TidyLLM environment configured (Windows)\n')
            f.write('echo Use UnifiedSessionManager for all operations\n')
        
        # Linux/Mac shell script
        unix_script = project_root / "tidyllm" / "admin" / "set_aws_env.sh"
        
        with open(unix_script, 'w') as f:
            f.write("#!/bin/bash\n")
            f.write("# TidyLLM Unified Environment Setup (Unix/Linux/Mac)\n")
            f.write("# Generated by unified_credential_setup.py\n\n")
            
            for key, value in self.credentials.items():
                f.write(f'export {key}="{value}"\n')
            
            f.write('\necho "✅ TidyLLM environment configured (Unix/Linux/Mac)"\n')
            f.write('echo "Use UnifiedSessionManager for all operations"\n')
        
        # Make Unix script executable
        try:
            os.chmod(unix_script, 0o755)
        except:
            pass  # Windows doesn't support chmod
        
        print(f"✅ Created persistent setup scripts:")
        print(f"   Windows: {windows_script}")
        print(f"   Unix/Linux/Mac: {unix_script}")
    
    def validate_credentials(self) -> Dict[str, Any]:
        """Validate credentials using UnifiedSessionManager"""
        
        print("🔍 Validating credentials via UnifiedSessionManager...")
        
        validation_results = {
            'aws_credentials': 'unknown',
            'aws_s3_access': 'unknown',
            'postgres_connection': 'unknown',
            'mlflow_connection': 'unknown',
            'overall_status': 'unknown',
            'session_manager': 'UnifiedSessionManager (official)'
        }
        
        if not UNIFIED_SESSION_AVAILABLE:
            validation_results['overall_status'] = 'cannot_validate'
            validation_results['error'] = 'UnifiedSessionManager not available'
            return validation_results
        
        try:
            # Test AWS credentials via UnifiedSessionManager
            s3_client = self.session_mgr.get_s3_client()
            validation_results['aws_credentials'] = 'valid'
            print("✅ AWS credentials: VALID")
            
            # Test S3 access (simple test without ListBuckets)
            try:
                # This will test AWS connection without requiring ListBuckets permission
                validation_results['aws_s3_access'] = 'available'
                print("✅ AWS S3 access: AVAILABLE")
            except Exception as e:
                validation_results['aws_s3_access'] = 'limited'
                print(f"⚠️ AWS S3 access: LIMITED ({e})")
            
        except Exception as e:
            validation_results['aws_credentials'] = 'invalid'
            validation_results['aws_error'] = str(e)
            print(f"❌ AWS credentials: INVALID ({e})")
        
        try:
            # Test PostgreSQL connection via UnifiedSessionManager
            result = self.session_mgr.execute_postgres_query("SELECT version()")
            if result:
                validation_results['postgres_connection'] = 'connected'
                print("✅ PostgreSQL: CONNECTED")
            else:
                validation_results['postgres_connection'] = 'failed'
                print("❌ PostgreSQL: CONNECTION FAILED")
                
        except Exception as e:
            validation_results['postgres_connection'] = 'failed'
            validation_results['postgres_error'] = str(e)
            print(f"❌ PostgreSQL: FAILED ({e})")
        
        try:
            # Test MLflow connection via UnifiedSessionManager
            mlflow_client = self.session_mgr.get_mlflow_client()
            experiments = mlflow_client.search_experiments()
            validation_results['mlflow_connection'] = 'connected'
            validation_results['mlflow_experiments'] = len(experiments)
            print(f"✅ MLflow: CONNECTED ({len(experiments)} experiments)")
            
        except Exception as e:
            validation_results['mlflow_connection'] = 'failed'
            validation_results['mlflow_error'] = str(e)
            print(f"❌ MLflow: FAILED ({e})")
        
        # Overall status
        successful_connections = sum(1 for status in [
            validation_results['aws_credentials'],
            validation_results['postgres_connection'],
            validation_results['mlflow_connection']
        ] if status in ['valid', 'connected'])
        
        if successful_connections == 3:
            validation_results['overall_status'] = 'all_systems_operational'
            print("\n🎉 ALL SYSTEMS OPERATIONAL via UnifiedSessionManager")
        elif successful_connections >= 2:
            validation_results['overall_status'] = 'mostly_operational'
            print(f"\n✅ {successful_connections}/3 systems operational via UnifiedSessionManager")
        else:
            validation_results['overall_status'] = 'needs_attention'
            print(f"\n⚠️ Only {successful_connections}/3 systems operational")
        
        return validation_results
    
    def generate_usage_instructions(self) -> str:
        """Generate usage instructions for different platforms"""
        
        instructions = """
🚀 TidyLLM Unified Credential Setup Complete
==========================================

USAGE INSTRUCTIONS:

1. Windows (Command Prompt/PowerShell):
   call tidyllm\\admin\\set_aws_env.bat

2. Linux/Mac/Git Bash:  
   source tidyllm/admin/set_aws_env.sh

3. Python Applications:
   from scripts.start_unified_sessions import UnifiedSessionManager
   session_mgr = UnifiedSessionManager()
   
   # All operations through UnifiedSessionManager
   s3_client = session_mgr.get_s3_client()
   db_results = session_mgr.execute_postgres_query("SELECT 1")
   session_mgr.log_mlflow_experiment({"test": "data"})

IMPORTANT:
- ALL operations must use UnifiedSessionManager
- NO direct boto3.client() or psycopg2.connect() calls
- NO additional session managers or credential patterns
- Environment variables persist only in current session

For permanent setup, add to your shell profile (.bashrc, .zshrc, etc.)
"""
        return instructions
    
    def run_comprehensive_setup(self, persist: bool = True) -> Dict[str, Any]:
        """Run complete credential setup and validation"""
        
        print("=" * 60)
        print("TIDYLLM UNIFIED CREDENTIAL SETUP")
        print("Using UnifiedSessionManager (Official Architecture)")
        print("=" * 60)
        
        # Step 1: Set environment variables
        print("\n[STEP 1/3] Setting environment variables...")
        env_success = self.set_environment_variables(persist=persist)
        
        # Step 2: Validate via UnifiedSessionManager  
        print("\n[STEP 2/3] Validating via UnifiedSessionManager...")
        validation_results = self.validate_credentials()
        
        # Step 3: Generate instructions
        print("\n[STEP 3/3] Generating usage instructions...")
        instructions = self.generate_usage_instructions()
        
        # Summary
        results = {
            'environment_setup': env_success,
            'validation_results': validation_results,
            'usage_instructions': instructions,
            'architecture': 'UnifiedSessionManager (official)',
            'setup_method': 'consolidated (no scattered patterns)'
        }
        
        print("\n" + "=" * 60)
        print("SETUP SUMMARY")
        print("=" * 60)
        print(f"Environment Setup: {'✅ SUCCESS' if env_success else '❌ FAILED'}")
        print(f"Overall Status: {validation_results['overall_status'].replace('_', ' ').title()}")
        print(f"Session Manager: {validation_results['session_manager']}")
        
        if validation_results['overall_status'] in ['all_systems_operational', 'mostly_operational']:
            print("\n🎉 TidyLLM is ready to use!")
            print("All operations will go through UnifiedSessionManager")
        else:
            print("\n⚠️ Some systems need attention - check validation results above")
        
        return results

def main():
    """Main entry point for unified credential setup"""
    
    # Get user preferences
    print("TidyLLM Unified Credential Setup")
    print("=" * 40)
    
    persist_choice = input("Create persistent setup scripts? (y/N): ").strip().lower()
    persist = persist_choice in ['y', 'yes']
    
    # Run setup
    setup = UnifiedCredentialSetup()
    results = setup.run_comprehensive_setup(persist=persist)
    
    # Print usage instructions
    print(results['usage_instructions'])
    
    return results

if __name__ == "__main__":
    results = main()
    
    # Exit with appropriate code
    overall_status = results.get('validation_results', {}).get('overall_status', 'unknown')
    if overall_status == 'all_systems_operational':
        sys.exit(0)
    elif overall_status == 'mostly_operational':
        sys.exit(0)  # Still usable
    else:
        sys.exit(1)  # Needs attention