#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Simple Database Connection Setup

This script helps you set up the connection to your Aurora PostgreSQL database.
"""

import os
import sys
import getpass

def create_env_file():
    """Create .env.local file with database connection details"""
    
    print("🗄️ Setting up Aurora PostgreSQL Connection")
    print("=" * 50)
    
    # Database connection details
    db_host = "vectorqa-cluster.cluster-cu562e4m02nq.us-east-1.rds.amazonaws.com"
    db_port = "5432"
    db_name = "vectorqa"
    db_user = "vectorqa_user"
    
    # Get password securely
    print("Enter password for {}: ".format(db_user))
    db_password = getpass.getpass()
    
    # Create environment variables
    env_content = """# Local Environment Configuration for Aurora PostgreSQL
# Generated by setup_db_simple.py

# Database Configuration
DB_HOST={}
DB_PORT={}
DB_NAME={}
DB_USER={}
DB_PASSWORD={}

# Full Database URL
DATABASE_URL=postgresql://{}:{}@{}:{}/{}

# AWS Configuration
AWS_REGION=us-east-1
AWS_RDS_ENDPOINT={}

# Application Configuration
ENVIRONMENT=local
DEBUG=true
LOG_LEVEL=INFO
""".format(db_host, db_port, db_name, db_user, db_password, 
           db_user, db_password, db_host, db_port, db_name, db_host)
    
    # Write to .env.local
    env_file_path = os.path.join(os.path.dirname(__file__), '..', '.env.local')
    
    try:
        with open(env_file_path, 'w') as f:
            f.write(env_content)
        
        print("✅ Environment file created: {}".format(env_file_path))
        print("⚠️  Remember to add .env.local to .gitignore to keep credentials secure!")
        
        return True
        
    except Exception as e:
        print("❌ Failed to create environment file: {}".format(e))
        return False

def test_connection():
    """Test the database connection"""
    
    print("\n🔍 Testing Database Connection")
    print("=" * 30)
    
    try:
        # Import here to avoid issues if not installed
        import psycopg2
        from dotenv import load_dotenv
        
        # Load environment variables
        load_dotenv('.env.local')
        
        # Get database URL from environment
        database_url = os.getenv('DATABASE_URL')
        
        if not database_url:
            print("❌ DATABASE_URL not found in environment")
            print("Please run create_env_file() first or set DATABASE_URL manually")
            return False
        
        # Test connection
        print("Connecting to database...")
        conn = psycopg2.connect(database_url)
        
        # Test basic query
        with conn.cursor() as cursor:
            cursor.execute("SELECT version();")
            version = cursor.fetchone()
            print("✅ Connected successfully!")
            print("Database: {}".format(version[0]))
        
        # Test pgvector extension
        with conn.cursor() as cursor:
            cursor.execute("SELECT * FROM pg_extension WHERE extname = 'vector';")
            vector_ext = cursor.fetchone()
            
            if vector_ext:
                print("✅ pgvector extension is available")
            else:
                print("⚠️  pgvector extension not found - you may need to enable it")
        
        # Test schema tables
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public'
                ORDER BY table_name;
            """)
            tables = cursor.fetchall()
            
            print("📋 Available tables ({}):".format(len(tables)))
            for table in tables:
                print("  - {}".format(table[0]))
        
        conn.close()
        return True
        
    except ImportError as e:
        print("❌ Missing dependency: {}".format(e))
        print("Please install: pip install psycopg2-binary python-dotenv")
        return False
    except Exception as e:
        print("❌ Connection failed: {}".format(e))
        return False

def main():
    """Main function to set up database connection"""
    
    print("🚀 Aurora PostgreSQL Connection Setup")
    print("=" * 50)
    
    # Step 1: Create environment file
    if create_env_file():
        # Step 2: Test connection
        if test_connection():
            print("\n🎉 Database connection setup complete!")
            print("\n📝 Next steps:")
            print("1. Your RAG orchestrator will now use the database")
            print("2. Test with: python scripts/test_database_connection.py")
            print("3. Run your enhanced QA demo with database integration")
        else:
            print("\n⚠️  Connection test failed. Please check your credentials.")
    else:
        print("❌ Setup failed. Please check your credentials and try again.")

if __name__ == "__main__":
    main()
