#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Database Connection Setup Script

This script helps you set up the connection to your Aurora PostgreSQL database
and test the connection.
"""

import os
import sys
import psycopg2
from psycopg2.extras import RealDictCursor
import getpass

def create_env_file():
    """Create .env.local file with database connection details"""
    
    print("🗄️ Setting up Aurora PostgreSQL Connection")
    print("=" * 50)
    
    # Database connection details
    db_host = "vectorqa-cluster.cluster-cu562e4m02nq.us-east-1.rds.amazonaws.com"
    db_port = "5432"
    db_name = "vectorqa"
    db_user = "vectorqa_user"
    
    # Get password securely
    db_password = getpass.getpass(f"Enter password for {db_user}: ")
    
    # Create environment variables
    env_content = f"""# Local Environment Configuration for Aurora PostgreSQL
# Generated by setup_database_connection.py

# Database Configuration
DB_HOST={db_host}
DB_PORT={db_port}
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}

# Full Database URL
DATABASE_URL=postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}

# AWS Configuration
AWS_REGION=us-east-1
AWS_RDS_ENDPOINT={db_host}

# Application Configuration
ENVIRONMENT=local
DEBUG=true
LOG_LEVEL=INFO
"""
    
    # Write to .env.local
    env_file_path = os.path.join(os.path.dirname(__file__), '..', '.env.local')
    
    try:
        with open(env_file_path, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Environment file created: {env_file_path}")
        print("⚠️  Remember to add .env.local to .gitignore to keep credentials secure!")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to create environment file: {e}")
        return False

def test_connection():
    """Test the database connection"""
    
    print("\n🔍 Testing Database Connection")
    print("=" * 30)
    
    # Get database URL from environment
    database_url = os.getenv('DATABASE_URL')
    
    if not database_url:
        print("❌ DATABASE_URL not found in environment")
        print("Please run create_env_file() first or set DATABASE_URL manually")
        return False
    
    try:
        # Test connection
        print("Connecting to database...")
        conn = psycopg2.connect(database_url)
        
        # Test basic query
        with conn.cursor() as cursor:
            cursor.execute("SELECT version();")
            version = cursor.fetchone()
            print(f"✅ Connected successfully!")
            print(f"Database: {version[0]}")
        
        # Test pgvector extension
        with conn.cursor() as cursor:
            cursor.execute("SELECT * FROM pg_extension WHERE extname = 'vector';")
            vector_ext = cursor.fetchone()
            
            if vector_ext:
                print("✅ pgvector extension is available")
            else:
                print("⚠️  pgvector extension not found - you may need to enable it")
        
        # Test schema tables
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public'
                ORDER BY table_name;
            """)
            tables = cursor.fetchall()
            
            print(f"📋 Available tables ({len(tables)}):")
            for table in tables:
                print(f"  - {table[0]}")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        return False

def setup_schema():
    """Set up the database schema if needed"""
    
    print("\n🏗️ Setting up Database Schema")
    print("=" * 30)
    
    database_url = os.getenv('DATABASE_URL')
    if not database_url:
        print("❌ DATABASE_URL not found")
        return False
    
    try:
        conn = psycopg2.connect(database_url)
        
        # Check if schema files exist
        schema_dir = os.path.join(os.path.dirname(__file__), '..', 'database', 'infra')
        
        if not os.path.exists(schema_dir):
            print(f"❌ Schema directory not found: {schema_dir}")
            return False
        
        schema_files = [
            'setup_database.sql',
            'complete_schema.sql',
            'embeddings_schema.sql',
            'review_schema.sql'
        ]
        
        for schema_file in schema_files:
            schema_path = os.path.join(schema_dir, schema_file)
            
            if os.path.exists(schema_path):
                print(f"📄 Found schema file: {schema_file}")
                
                # Read and execute schema
                with open(schema_path, 'r') as f:
                    schema_sql = f.read()
                
                try:
                    with conn.cursor() as cursor:
                        cursor.execute(schema_sql)
                    conn.commit()
                    print(f"✅ Executed schema: {schema_file}")
                    
                except Exception as e:
                    print(f"⚠️  Schema {schema_file} may already exist or have errors: {e}")
            else:
                print(f"⚠️  Schema file not found: {schema_file}")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Schema setup failed: {e}")
        return False

def main():
    """Main function to set up database connection"""
    
    print("🚀 Aurora PostgreSQL Connection Setup")
    print("=" * 50)
    
    # Step 1: Create environment file
    if create_env_file():
        # Step 2: Load environment variables
        from dotenv import load_dotenv
        load_dotenv('.env.local')
        
        # Step 3: Test connection
        if test_connection():
            # Step 4: Setup schema (optional)
            setup_choice = input("\n🤔 Do you want to set up the database schema? (y/n): ")
            if setup_choice.lower() in ['y', 'yes']:
                setup_schema()
        
        print("\n🎉 Database connection setup complete!")
        print("\n📝 Next steps:")
        print("1. Your RAG orchestrator will now use the database")
        print("2. Test with: python scripts/test_database_connection.py")
        print("3. Run your enhanced QA demo with database integration")
        
    else:
        print("❌ Setup failed. Please check your credentials and try again.")

if __name__ == "__main__":
    main()
