#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
📊 Report Viewer - Show All Available Reports

This script shows you all the available reports and their locations.
It helps you understand what data has been generated and where to find it.

Usage:
    python3 show_reports.py
"""

import os
import json
import glob
from datetime import datetime

def print_header(title: str):
    """Print a formatted header."""
    print("\n" + "="*80)
    print(f"📊 {title}")
    print("="*80)

def print_section(title: str):
    """Print a formatted section."""
    print(f"\n📋 {title}")
    print("-" * 60)

def get_file_info(filepath: str) -> dict:
    """Get information about a file."""
    if not os.path.exists(filepath):
        return {"exists": False}
    
    stat = os.stat(filepath)
    size_kb = stat.st_size / 1024
    
    return {
        "exists": True,
        "size_kb": round(size_kb, 2),
        "modified": datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
        "lines": sum(1 for _ in open(filepath)) if size_kb > 0 else 0
    }

def show_json_report_summary(filepath: str, title: str):
    """Show a summary of a JSON report."""
    info = get_file_info(filepath)
    
    if not info["exists"]:
        print(f"❌ {title}: File not found")
        return
    
    print(f"✅ {title}")
    print(f"   📁 Location: {filepath}")
    print(f"   📏 Size: {info['size_kb']} KB")
    print(f"   📅 Modified: {info['modified']}")
    print(f"   📄 Lines: {info['lines']}")
    
    # Try to show a brief summary
    try:
        with open(filepath, 'r') as f:
            data = json.load(f)
        
        if "test_summary" in data:
            summary = data["test_summary"]
            print(f"   📊 Tests: {summary.get('total_tests', 'N/A')}")
            print(f"   ⏱️ Duration: {summary.get('duration_seconds', 'N/A')} seconds")
        
        elif "statistics" in data:
            stats = data["statistics"]
            print(f"   📈 Average Risk Score: {stats.get('average_risk_score', 'N/A')}")
            print(f"   ⏱️ Average Response Time: {stats.get('average_response_time', 'N/A')} ms")
        
        elif "timestamp" in data:
            print(f"   📅 Generated: {data['timestamp']}")
            
    except Exception as e:
        print(f"   ⚠️ Could not parse JSON: {str(e)}")

def show_log_file_summary(filepath: str, title: str):
    """Show a summary of a log file."""
    info = get_file_info(filepath)
    
    if not info["exists"]:
        print(f"❌ {title}: File not found")
        return
    
    print(f"✅ {title}")
    print(f"   📁 Location: {filepath}")
    print(f"   📏 Size: {info['size_kb']} KB")
    print(f"   📅 Modified: {info['modified']}")
    print(f"   📄 Lines: {info['lines']}")
    
    # Show last few lines if it's a log file
    if info['lines'] > 0:
        try:
            with open(filepath, 'r') as f:
                lines = f.readlines()
                if lines:
                    last_line = lines[-1].strip()
                    if len(last_line) > 100:
                        last_line = last_line[:100] + "..."
                    print(f"   📝 Last Entry: {last_line}")
        except Exception as e:
            print(f"   ⚠️ Could not read file: {str(e)}")

def main():
    """Main function to show all reports."""
    print_header("REPORT VIEWER - ALL AVAILABLE REPORTS")
    print("This shows you all the reports and logs that have been generated by the system.")
    
    # Test Reports
    print_section("TEST REPORTS")
    
    test_reports = [
        ("manual_test_report_20250822_043736.json", "Manual Test Report (Latest)"),
        ("performance_test_results.json", "Performance Test Results"),
        ("realistic_performance_results.json", "Realistic Performance Test Results"),
        ("production_performance_results.json", "Production Performance Test Results"),
        ("log_analysis_report.json", "Log Analysis Report")
    ]
    
    for filepath, title in test_reports:
        show_json_report_summary(filepath, title)
    
    # Log Files
    print_section("LOG FILES")
    
    log_files = [
        ("data/logs/dspy_errors.log", "DSPy Errors Log"),
        ("data/logs/fallback_usage.log", "Fallback Usage Log"),
        ("data/logs/performance_metrics.log", "Performance Metrics Log"),
        ("data/logs/sme_analysis.log", "SME Analysis Log"),
        ("data/logs/context_errors.log", "Context Errors Log"),
        ("data/logs/database_errors.log", "Database Errors Log"),
        ("data/logs/import_errors.log", "Import Errors Log")
    ]
    
    for filepath, title in log_files:
        show_log_file_summary(filepath, title)
    
    # Find all manual test reports
    print_section("ALL MANUAL TEST REPORTS")
    manual_reports = glob.glob("manual_test_report_*.json")
    
    if manual_reports:
        for report in sorted(manual_reports, reverse=True):  # Most recent first
            timestamp = report.replace("manual_test_report_", "").replace(".json", "")
            try:
                dt = datetime.strptime(timestamp, "%Y%m%d_%H%M%S")
                formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S")
                show_json_report_summary(report, f"Manual Test Report ({formatted_time})")
            except:
                show_json_report_summary(report, f"Manual Test Report ({timestamp})")
    else:
        print("❌ No manual test reports found")
    
    # Summary
    print_section("SUMMARY")
    
    total_files = 0
    total_size = 0
    
    for filepath, _ in test_reports + log_files:
        info = get_file_info(filepath)
        if info["exists"]:
            total_files += 1
            total_size += info["size_kb"]
    
    print(f"📊 Total Files: {total_files}")
    print(f"📏 Total Size: {round(total_size, 2)} KB")
    print(f"📅 Generated: Various times during testing")
    
    print_section("HOW TO USE THESE REPORTS")
    print("1. 📊 Test Reports: Show how the system responded to different scenarios")
    print("2. 📝 Log Files: Show detailed system activity and errors")
    print("3. 📈 Performance Reports: Show system performance metrics")
    print("4. 🔍 Analysis Reports: Show patterns and insights from the data")
    
    print("\n💡 To run new tests:")
    print("   python3 manual_test_scenarios.py")
    print("\n💡 To analyze logs:")
    print("   python3 src/backend/mcp/utils/log_analyzer.py")
    
    print_header("REPORT VIEWING COMPLETE")

if __name__ == "__main__":
    main()
