#!/usr/bin/env python3
"""
Standardized Launcher for TidyLLM Vector QA System
Generated by TidyLLM Universal Streamlit Launcher System
"""

import sys
from pathlib import Path

# Add scripts directory to path
sys.path.append(str(Path(__file__).parent))

from start_streamlit_universal import StreamlitDemoLauncher
import argparse

def main():
    parser = argparse.ArgumentParser(
        description="Vector-based question answering",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        "--install-deps", 
        action="store_true",
        help="Install/update requirements before launching"
    )
    
    parser.add_argument(
        "--no-logs", 
        action="store_true",
        help="Don't show Streamlit logs in console"
    )
    
    args = parser.parse_args()
    
    launcher = StreamlitDemoLauncher("vectorqa")
    
    # Register cleanup on exit
    import atexit
    atexit.register(launcher.cleanup)
    
    try:
        success = launcher.full_launch_sequence(
            install_deps=args.install_deps,
            show_logs=not args.no_logs
        )
        
        if not success:
            sys.exit(1)
            
    except KeyboardInterrupt:
        print("\nGoodbye!")
        launcher.cleanup()
    except Exception as e:
        print(f"Unexpected error: {e}")
        launcher.cleanup()
        sys.exit(1)

if __name__ == "__main__":
    main()
