#!/bin/bash
# TidyLLM Project Unpacking Script
# Generated by pack_project.py

set -euo pipefail

echo "TidyLLM Project Unpacker"
echo "========================"

PKG_DIR="packages"
if [ ! -d "$PKG_DIR" ]; then
  echo "Error: packages directory not found!"
  echo "Run this script from the directory containing the 'packages' folder."
  exit 1
fi

PROJECT_DIR="TidyLLM_unpacked"
echo "Creating project directory: $PROJECT_DIR"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

echo "Unpacking packages..."
shopt -s nullglob
for zip_file in ../$PKG_DIR/*.zip; do
  echo "  Unpacking $(basename "$zip_file")..."
  unzip -q "$zip_file"
done

echo "Unpacking complete!"
echo "Project restored to: $PROJECT_DIR"
echo
echo "Next steps:"
echo "1) cd $PROJECT_DIR"
echo "2) pip install -e ."
echo "3) python qa_processor.py --setup || true"
