[server]
runOnSave = true
enableCORS = false
enableXsrfProtection = false
port = 8501
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
fastReruns = true
magicEnabled = true

[global]
developmentMode = false
